### ISSUE TITLE
Can you add this txt format?

### ISSUE THREAD

**Issue by SolsticeSpectrum** [hhhzzzsss/SongPlayer#11]
Inertia and BleachHack and probably others have recording functionality, it records in this format

```
0:12:3
6:14:3
10:12:3
12:12:3
18:14:3
22:12:3
24:12:3
30:14:3
```

`tick:tone:instrument`

I recorded some beautiful songs from skilled noteblock musicians such as 
https://www.youtube.com/@acatterz

You can get them here:
https://github.com/DarkReaper231/darkhack-resources/raw/main/notebot/songs.zip

Here is the songlist:
https://github.com/DarkReaper231/darkhack-resources/blob/main/songlist.txt

These songs usually sound better than what you get from midi and nbs so it would be really nice to include this format

**Comment by Sk8kman** [comment]
I know this is a tad late (almost a year lol) but I added this functionality in my fork of SongPlayer which you can find on my github if ur still wanting it

**Comment by DarkReaper231** [comment]
> I know this is a tad late (almost a year lol) but I added this functionality in my fork of SongPlayer which you can find on my github if ur still wanting it

Yes I am actually, thanks a lot for the effort! I'm gonna check it out.

**Comment by Sk8kman** [comment]
Haha thank you! I made the .txt support a month or so ago but didn't release it until earlier today. I'll edit the changelogs to include that commenting feature, which I honestly forgot I added lol. Thanks for trying my fork out!

**Comment by hhhzzzsss** [comment]
Added
