### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by Poopooracoocoo** [hhhzzzsss/SongPlayer#14]
Please and thank you! :)

**Comment by Poopooracoocoo** [comment]
> Do it yourself

Very valid but I didn't demand for anything, nor did I harass the author, or create a duplicate. I actually opened this after seeing someone try to get this running on their 1.19.4 instance in the Fabric Discord so I opened this issue for them. I don't use this mod personally.

**Comment by I-Got-You-Dead2** [comment]
Do it yourself
