### ISSUE TITLE
Survival mode

### ISSUE THREAD

**Issue by herculescoding93** [hhhzzzsss/SongPlayer#15]
i suggest that there should be a command toggling survival mode, meaning that when u select a song with $play, it will show an overlay of what blocks should be placen as instruments and then the mod, provided noteblocks from the hotbar, would place the noteblocks on top of the blocks, and then tune them in survival mode, essentially turning this mod into survival compatible so u dont need creative to play epic songs

**Comment by I-Got-You-Dead2** [comment]
Not possible with the tuning method used

**Comment by loadClass** [comment]
agree

**Comment by hhhzzzsss** [comment]
Added a "survival only" mode that requires you to place the required instruments for a song within reach distance manually, then tunes them automatically when you play the song.
