### ISSUE TITLE
Unknown or incomplete command gms

### ISSUE THREAD

**Issue by amongussussy-baka** [hhhzzzsss/SongPlayer#17]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/132794240/236652615-41676ef8-6b43-43ec-8427-335402a9166f.png">
this comes whenever I try to play a song ;-; can anyone help?

**Comment by I-Got-You-Dead2** [comment]
Maybe because the server doesn’t have essentials?

**Comment by amongussussy-baka** [comment]
essentials?
wdym?
(on a singleplayer world btw)

**Comment by I-Got-You-Dead2** [comment]
It’s a plugin

**Comment by I-Got-You-Dead2** [comment]
Bruh some people 

use $usevanillacommands

**Comment by amongussussy-baka** [comment]
ah
thank you
