### ISSUE TITLE
this isnt an issue but add this pls

### ISSUE THREAD

**Issue by Sniper3d107** [hhhzzzsss/SongPlayer#24]
like add a thing where u can make it survival, so like if u have noteblocks setup, it will tell u what notes u need

**Comment by Sniper3d107** [comment]
also can u update 1.19.4

**Comment by Sk8kman** [comment]
I added this feature in my fork of songplayer if u want to give it a try

**Comment by hhhzzzsss** [comment]
Added a "survival only" mode that requires you to place the required instruments for a song within reach distance manually, then tunes them automatically when you play the song.
