### ISSUE TITLE
in survival server

### ISSUE THREAD

**Issue by Noda-dalad** [hhhzzzsss/SongPlayer#25]
Please add a mode that does not require op

After typing $play <song>
Prompt number of note blocks
and the number of blocks to adjust the tone in chat room

I need to use it in servival servers

**Comment by has-7** [comment]
same.

**Comment by Sk8kman** [comment]
I added this feature on my fork of SongPlayer if you want to give it a try

**Comment by MrLitePLIK** [comment]
@Sk8kman thanks for your work ! ! !

**Comment by flaryx32** [comment]
@Sk8kman would you care to update the fork to 1.20.4? or either make a pull request??

**Comment by Sk8kman** [comment]
@flaryx32 my fork should already work with 1.20.4

**Comment by hhhzzzsss** [comment]
Added a "survival only" mode that requires you to place the required instruments for a song within reach distance manually, then tunes them automatically when you play the song.
