### ISSUE TITLE
add a command to turn off nbt

### ISSUE THREAD

**Issue by anthony1204** [hhhzzzsss/SongPlayer#30]
on most creative servers, you have to pay to use nbt or it is disabled. add a setting that toggles nbt on/off.

**Comment by Sk8kman** [comment]
SongPlayer can't work without writing NBT to items because it's required to give the noteblocks their instrument and pitch.

**Comment by anthony1204** [comment]
You could try meteor client notebook cuz it doesn't place it automatically but it turned them automatically

**Comment by RealIceCone** [comment]
meteor client notebot sucks they they could make it so that you can click the noteblocks yes but it would need too place blocks under the noteblocks and that would not matter becuse song player allready uses creative to get the noteblocks.

**Comment by RealIceCone** [comment]
> meteor client notebot sucks they they could make it so that you can click the noteblocks yes but it would need too place blocks under the noteblocks and that would not matter becuse song player allready uses creative to get the noteblocks.

i meant that it should be an option where song player hits the notes until they are correct lol

**Comment by hhhzzzsss** [comment]
You can sort of do this with survival-only mode now. You will have to set yourself into survival mode manually when you do that, though.
