### ISSUE TITLE
1.20.2 support (if possible)

### ISSUE THREAD

**Issue by hqnt** [hhhzzzsss/SongPlayer#34]
Hey, I noticed that you skipped 1.20.2 support and went straight to 1.20.3 and 4 and I currently use mods that are so far only on 1.20.2

**Comment by Sk8kman** [comment]
Hey I have a fork of SongPlayer that's compatible with 1.20.2 on my GitHub if you want to use that temporarily.

**Comment by hqnt** [comment]
Yeah sure that can work!

**Comment by hhhzzzsss** [comment]
There is now a 1.20.2 backport [here](https://modrinth.com/mod/songplayer/version/HzCClbUB).
