### ISSUE TITLE
the prefixes

### ISSUE THREAD

**Issue by sofbeofb** [hhhzzzsss/SongPlayer#35]
One day, i accidentally typed "$prefix /". Because of that, I am unable to use the songplayer mod. Every command ends up with a failed command, and i cannot change the prefix back. Uninstalling and reinstalling doesnt work too. Does anyone know a way to fix this?

**Comment by Sk8kman** [comment]
Close minecraft, go to your .minecraft folder, there should be a SongPlayer folder. Go in that and delete the .json file. That should reset SongPlayer's settings.

**Comment by hhhzzzsss** [comment]
I changed the setPrefix command to stop you from setting your prefix to "/".
