### ISSUE TITLE
not quite an issue

### ISSUE THREAD

**Issue by WillHanighen** [hhhzzzsss/SongPlayer#37]
please please please please please port to 1.20.2 please please pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee i dont want to update my modpack againnn

**Comment by Sk8kman** [comment]
I have a version of SongPlayer compatible with 1.20.2 on my github if you want to use that for the time being. Just keep in mind it's based off of v2.0, so some features are missing.

**Comment by hhhzzzsss** [comment]
There is now a 1.20.2 backport [here](https://modrinth.com/mod/songplayer/version/HzCClbUB).
