### ISSUE TITLE
Survival support

### ISSUE THREAD

**Issue by TheBosoYolo** [hhhzzzsss/SongPlayer#40]
Would be nice if a survival support was made, where the client can work even without creative mode. It would either place the noteblocks from the inventory with the nbt (if possible) or utilize already placed noteblocks

**Comment by YukihaYukishiro** [comment]
Same.
I actually don't understand why It's not coded like that in the first place.

**Comment by denisapain** [comment]
i use songplayer with metoer which has notebot

**Comment by hhhzzzsss** [comment]
Added a "survival only" mode that requires you to place the required instruments for a song within reach distance manually, then tunes them automatically when you play the song.
