### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by SamMc1** [hhhzzzsss/SongPlayer#44]
its working but the time i do $play [songname] it builds the stuff then it will do the command /gms and gms does not work in 1.20.4

**Comment by hhhzzzsss** [comment]
Is the problem that the `/gms` and `/gmc` commands do not exist? Those commands only exist when the server is using the essentials plugin. If you are playing, for example, on a fully vanilla server, you should run $useVanillaCommands. That way, it will use `/gamemode survival` and `/gamemode creative` instead. You can also specifically set what survival or creative with  commands to use with `/setSurvivalCommand` and `/setCreativeCommand` if the server you are playing on uses neither.

If it's not that issue, please tell me what error it gives, if any.

**Comment by SamMc1** [comment]
oh thank you
