### ISSUE TITLE
invalid song format issue

### ISSUE THREAD

**Issue by Yoltznvolts** [hhhzzzsss/SongPlayer#46]
whenever i try to play a song it says invalid song format please help!

**Comment by Sk8kman** [comment]
SongPlayer can only play .midi .mid .nbs and .txt files. If you are trying to play .mp3 .mp4 etc... It won't work. If you are using a supported format I can take a look at the file and see what's going wrong

**Comment by Yoltznvolts** [comment]
here is the file

[467339_At_the_Speed_of_Light_FINA - Copy.txt](https://github.com/user-attachments/files/15754512/467339_At_the_Speed_of_Light_FINA.-.Copy.txt)

**Comment by Yoltznvolts** [comment]
it was origanally a nbs but i have to change it into a txt for it to work

**Comment by Sk8kman** [comment]
That file seems to have MP3 related data in it, not nbs or txt

**Comment by Yoltznvolts** [comment]
the download was a mp3 but i changed it to nbs does it stay mp3 data?

**Comment by Sk8kman** [comment]
renaming the file extension to .nbs doesn't change the data inside the file. It's still an mp3

**Comment by Yoltznvolts** [comment]
oh how do i change it to a nbs data?

**Comment by Sk8kman** [comment]
There aren't any good ways to accurately convert mp3 files to .nbs files, but you can usually search online for a .midi or .nbs file someone made.
https://drive.google.com/file/d/1yDcV4XxfzhmdH4NWGGzMxHFFc9IigjZs/view?pli=1
here's a link of a proper .nbs file that's compatible with SongPlayer

**Comment by Yoltznvolts** [comment]
ok thanks i think thats it
