### ISSUE TITLE
Survival compatibility?

### ISSUE THREAD

**Issue by TahoeBennie** [hhhzzzsss/SongPlayer#6]
It plays the notes in survival as it has to, so it might as well place the noteblocks in survival if there are enough in the player's inventory, making oneself able to use the mod on any ordinary survival server.
Edit, i just realized that it needs creative to get the note blocks pre-tuned, so something to do instead would be to make it manually tune all of them, and even though thats less efficient, it will work in survival, which is the goal here. It would also be nice to see it default to manually tuning the noteblocks if it failed to switch to creative and there are enough noteblocks in the player's inventory.
Edit 2, i just realized that you need to have the noteblocks with predetermined nbt data to set what note it is. I don't know if there is any way around placing the block the actual note comes from so I'm just going to leave this open as there might be a way that I just can't think of right now.

**Comment by Joshua11TheHacker** [comment]
like it can be possible that the client can just tune it btw is it a virus?`???

**Comment by I-Got-You-Dead** [comment]
> It plays the notes in survival as it has to, so it might as well place the noteblocks in survival if there are enough in the player's inventory, making oneself able to use the mod on any ordinary survival server.
> 
> Edit, i just realized that it needs creative to get the note blocks pre-tuned, so something to do instead would be to make it manually tune all of them, and even though thats less efficient, it will work in survival, which is the goal here. It would also be nice to see it default to manually tuning the noteblocks if it failed to switch to creative and there are enough noteblocks in the player's inventory.
> 
> Edit 2, i just realized that you need to have the noteblocks with predetermined nbt data to set what note it is. I don't know if there is any way around placing the block the actual note comes from so I'm just going to leave this open as there might be a way that I just can't think of right now.

Not how it works, it needs gmc to modify the nbt data of the noteblocks

**Comment by I-Got-You-Dead** [comment]
> like it can be possible that the client can just tune it btw is it a virus?`???

Stfu

**Comment by hhhzzzsss** [comment]
Yeah, it would have to behave pretty differently in survival. I'll close this issue for now since I don't have any plans to make something like that at the moment.
