### ISSUE TITLE
Mod breaks in 1.19.2 as opposed to 1.19

### ISSUE THREAD

**Issue by TahoeBennie** [hhhzzzsss/SongPlayer#9]
The mod crashes the moment it tries to run a survival or creative command in version 1.19.2, probably also 1.19.1. I'm guessing this is because of the way the new chat has been implemented, and that is enough to break the automatic commands from this mod.

**Comment by rfl890** [comment]
working on a fix for this

**Comment by I-Got-You-Dead** [comment]
Download this repo and build it, it works on 1.19.2

https://github.com/mdo992/SongPlayer

**Comment by Caketaco** [comment]
@hhhzzzsss yo can you built this and shove it into releases

**Comment by mdo992** [comment]
> @mdo992 yo can you build the 1.19.2 fork and shove it into your fork's releases

alr i’ll also port to 1.19.3 if there needs changes

**Comment by Caketaco** [comment]
Lmk where it’s posted

**Comment by mdo992** [comment]
> Lmk where it’s posted

sorry forgot abt this pr for a bit, heres the jar: https://github.com/mdo992/SongPlayer/releases/tag/v2.0.1

**Comment by Spicy-Axolotl** [comment]
@mdo992 Sorry to bother you but, is it possible for you to compile a version for 1.19.2? I tried compiling it myself and didn't have any luck. Thanks!

**Comment by mdo992** [comment]
> @mdo992 Sorry to bother you but, is it possible for you to compile a version for 1.19.2? I tried compiling it myself and didn't have any luck. Thanks!

https://github.com/mdo992/SongPlayer/releases

**Comment by Spicy-Axolotl** [comment]
> https
Thank you so much!

**Comment by hhhzzzsss** [comment]
I merged your mdo's 1.19.3 pr, thanks for the help!
